name: ML Pipeline CI/CD

on:
  push:
    branches: [dev, staging, main, feature1, feature2]
  pull_request:
    branches: [dev, staging, main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest
      run: |
        pytest tests/ -v
        
    - name: Format check with Black
      run: |
        black --check .

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t mlops-app:latest .
        
    - name: Test Docker image
      run: |
        docker run --rm mlops-app:latest python -c "import pandas as pd; print('Docker test successful!')"

  dvc-pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup DVC
      uses: iterative/setup-dvc@v1
      
    - name: DVC Pull
      run: |
        dvc pull
        
    - name: Run DVC Pipeline
      run: |
        echo "DVC pipeline would run here"